<?php

namespace App\Middleware;

use App\Helpers\DateTimeHelper;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use \Psr\Http\Server\RequestHandlerInterface;
use App\Helpers\LogHelper;
use Psr\Http\Server\MiddlewareInterface;
use App\Models\AccessLogModel;
use UnexpectedValueException;
use Firebase\JWT\JWT as JWT;
use Firebase\JWT\Key;
use App\Exceptions\HttpInvalidInputsException;


/**
 * LogMiddleware class is responsible for logging access information to the database
 * and handling log messages for user requests.
 *
 * This middleware processes HTTP requests, extracts relevant details like
 * IP address, resource URI, and request method, and optionally decodes
 * a JWT token to log user-specific information.
 */
class LogMiddleware implements MiddlewareInterface
{
    /**
     * Constructor for the LogMiddleware class.
     *
     * @param AccessLogModel $accessLogModel Model instance to log data into the database.
     */
    public function __construct(private AccessLogModel $accessLogModel) {}
    /**
     * Process the incoming server request and log access details.
     * Extracts IP address, resource URI, and request method from the server.
     * If a JWT token is provided in the request's Authorization header,
     * decodes the token to retrieve user information and logs it into the database.
     *
     * @param RequestInterface $request The user request
     * @param RequestHandlerInterface $handler The request handler for generating the response.
     * @return ResponseInterface The response generated by the handler.
     */
    public function process(RequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        //? Ask teacher: is it better to fetch from the server or from the request ?
        //get the information from the server
        $ip_address = $_SERVER["REMOTE_ADDR"];
        //by default, the date and time is added to the message
        $resource_uri = $_SERVER["REQUEST_URI"];
        $request_method = $_SERVER["REQUEST_METHOD"];
        $queryString = $request->getUri()->getQuery();
        $log_message = "\nTest message" . "\nClient IP address: " . $ip_address . "\nResource uri: " . $resource_uri . "\nRequest method: " . $request_method . "\nQuery strings: " . $queryString;

        //TODO: get the decoded token to get information about the user

        $auth_header = $request->getHeaderLine("Authorization");
        $jwt = str_replace("Bearer ", "", $auth_header);
        $date = new DateTimeHelper();
        $time = $date->nowForDb();
        // try {
        //for now, this will stop the issues ig
        if ($jwt != null) {
            $decoded_token = (array)(JWT::decode($jwt, new Key(SECRET_KEY, "HS256")));

            $log_information = [
                "user_id" => 1,
                "email" => $decoded_token["email"],
                "ip_address" => $ip_address,
                "method" => $request_method,
                "logged_at" => $time
            ];
            //log into db
            $this->accessLogModel->insertLogDb($log_information);
        }
        LogHelper::handleAccess($log_message);

        return $handler->handle($request);
    }
}
